apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lb-ingress1
spec:
  rules:
  - host: poc1.microservice.com
    http:
      paths:
      - path: /pricesvc*
        backend:
          serviceName: priceinfo-ingress-service
          servicePort: 80
      - path: /inventorysvc/*
        backend:
          serviceName: inventory-ingress-service
          servicePort: 80
