apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lb-ingress1
spec:
  rules:
  - host: ms.poc.com
    http:
      paths:
      - path: /pricesvc
        backend:
          serviceName: priceinfo-ingress-service
          servicePort: 80
  - host: poc.microservice.com
    http:
      paths:
      - path: /pricesvc*
        backend:
          serviceName: priceinfo-ingress-service
          servicePort: 80
      - path: /inventorysvc/*
        backend:
          serviceName: inventory-ingress-service
          servicePort: 80
      - path: /productinfosvc/
        backend:
          serviceName: product-ingress-service
          servicePort: 80
