apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ms-nginx-ingress
  namespace: production
spec:
  backend:
    serviceName: default-handler
    servicePort: 80
  rules:
  - host: microservice.poc.com
    http:
      paths:
      - path: /pricesvc/manage/health
        backend:
          serviceName: priceinfo-backend-service
          servicePort: 80
      - path: /inventorysvc
        backend:
          serviceName: inventory-backend-service
          servicePort: 80
      - path: /productinfosvc/manage/health
        backend:
          serviceName: product-ingress-service
          servicePort: 8080
