apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: browse-frontend-production
  namespace: production
spec:
  replicas: 3
  template:
    metadata:
      name: frontend
      labels:
        app: browse-ui
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/microservice-poc/browser-ui:1.0.0
        imagePullPolicy: Always
        ports:
        - name: frontend
          containerPort: 8080
