apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: priceinfo-backend-production
  namespace: production
spec:
  replicas: 3
  template:
    metadata:
      name: backend
      labels:
        app: priceinfo-svc
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/microservice-poc/priceinfo-svc:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /pricesvc/manage/health
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 50
          successThreshold: 2
          failureThreshold: 5
        ports:
        - name: backend
          containerPort: 8080
