apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: priceinfo-backend-production
  namespace: production
spec:
  replicas: 3
  template:
    metadata:
      name: backend
      labels:
        app: priceinfo-svc
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/microservice-poc/priceinfo-svc:1.0.0
        imagePullPolicy: Always
        command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080
