apiVersion: v1
kind: Service
metadata:
  name: inventory-backend-service
  namespace: production
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8081
    protocol: TCP
  selector:
    role: backend
    app: inventory-svc
