apiVersion: v1
kind: Service
metadata:
  name: inventory-ingress-service
  namespace: production
  labels:
    app: inventory-svc
    role: backend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: inventory-svc
    role: backend
