apiVersion: v1
kind: Service
metadata:
  name: priceinfo-backend-service
  namespace: production
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    role: backend
    app: priceinfo-svc
