apiVersion: v1
kind: Service
metadata:
  name: priceinfo-backend-service
  namespace: production
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: priceinfo-svc
    role: backend

---

apiVersion: v1
kind: Service
metadata:
  name: priceinfo-ingress-service
  namespace: production
  labels:
    app: priceinfo-svc
    role: backend    
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: priceinfo-svc
    role: backend
