apiVersion: v1
kind: Service
metadata:
  name: priceinfo-backend-service1
  namespace: production
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: priceinfo-svc
    role: backend
