apiVersion: v1
kind: Service
metadata:
  name: priceinfo-backend-service1
  namespace: production
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: gceme
    role: frontend
