apiVersion: v1
kind: Service
metadata:
  name: product-backend-service
  namespace: production
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    role: backend
    app: product-svc
