apiVersion: v1
kind: Service
metadata:
  name: product-ingress-service
  namespace: production
  labels:
    app: product-svc
    role: backend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: product-svc
    role: backend
