  apiVersion: v1
  kind: Service
  metadata:
    name: product-service
    namespace: production
  spec:
    type: NodePort
    selector:
      app: product-svc
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8082