apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-backend-canary
  namespace: production
spec:
  replicas: 3
  template:
    metadata:
      name: backend
      labels:
        app: product-svc
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/microservice-poc/product-svc:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /productsvc/manage/health
            port: 8082
        command: ["sh", "-c", "app -port=8082"]
        ports:
        - name: backend
          containerPort: 8082
