  apiVersion: v1
  kind: Service
  metadata:
    name: inventory-service
    namespace: production
  spec:
    type: NodePort
    selector:
      app: inventory-svc
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8081

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-backend-production
spec:
  replicas: 3
  template:
    metadata:
      name: backend
      labels:
        app: inventory-svc
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/microservice-poc/inventory-svc:1.0.0
        resources:
          limits:
            memory: "1500Mi"
            cpu: "200m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /inventorysvc/manage/health
            port: 8081
        command: ["sh", "-c", "app -port=8081"]
        ports:
        - name: backend
          containerPort: 8081