  apiVersion: v1
  kind: Service
  metadata:
    name: priceinfo-service
    namespace: production
  spec:
    type: NodePort
    selector:
      app: priceinfo-svc
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: priceinfo-backend-production
spec:
  replicas: 3
  template:
    metadata:
      name: backend
      labels:
        app: priceinfo-svc
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/microservice-poc/priceinfo-svc:1.0.0
        resources:
          limits:
            memory: "1500Mi"
            cpu: "200m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /pricesvc/manage/health
            port: 8080
        command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080